package hello;
// Generated Sep 1, 2017 12:14:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Libro generated by hbm2java
 */
@Entity
public class Libro  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Autor> autors = new HashSet<Autor>(0);

    public Libro() {
    }

    public Libro(String nombre, Set<Autor> autors) {
       this.nombre = nombre;
       this.autors = autors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="libro")
    public Set<Autor> getAutors() {
        return this.autors;
    }
    
    public void setAutors(Set<Autor> autors) {
        this.autors = autors;
    }




}


